export enum SESSION_STATE {
  CONFLICT = "CONFLICT",
  CONNECTED = "CONNECTED",
  DEPRECATED_VERSION = "DEPRECATED_VERSION",
  OPENING = "OPENING",
  PAIRING = "PAIRING",
  PROXYBLOCK = "PROXYBLOCK",
  SMB_TOS_BLOCK = "SMB_TOS_BLOCK",
  TIMEOUT = "TIMEOUT",
  TOS_BLOCK = "TOS_BLOCK",
  UNLAUNCHED = "UNLAUNCHED",
  UNPAIRED = "UNPAIRED",
  UNPAIRED_IDLE = "UNPAIRED_IDLE",
  DISCONNECTED = "DISCONNECTED",
  RESUMING = "RESUMING",
  SYNCING = "SYNCING",
}

export enum SESSION_STATUS {
  IS_LOGGED = "isLogged",
  NOT_LOGGED = "notLogged",
  BROWSER_CLOSE = "browserClose",
  QR_READ_SUCCESS = "qrReadSuccess",
  QR_READ_FAIL = "qrReadFail",
  AUTOCLOSE_CALLED = "autocloseCalled",
  DISCONNECTED_MOBILE = "desconnectedMobile",
  DELETE_TOKEN = "deleteToken",
}
